management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://89.19.23.50:9411/api/v2/spans

redis:
  service:
    prefix: CMN-SW:RDS
    ttl: 3000
    cacheable:
      ttl: 180
  server:

    port: 6379
    cluster:
      nodes:
    password:
    environment: live
