apiVersion: v1
kind: Service
metadata:
  name: basket-service
  labels:
    app: basket-service
spec:
  ports:
  - port: 9006
    protocol: TCP
  clusterIP: None
  selector:
    app: basket-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basket-service
  labels:
    app: basket-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basket-service
  template:
    metadata:
      labels:
        app: basket-service
    spec:
      containers:
      - name: basket-service
        image: basket-service
