apiVersion: v1
kind: Service
metadata:
  name: log-service
  labels:
    app: log-service
spec:
  ports:
  - port: 9007
    protocol: TCP
  clusterIP: None
  selector:
    app: log-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-service
  labels:
    app: log-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-service
  template:
    metadata:
      labels:
        app: log-service
    spec:
      containers:
      - name: log-service
        image: log-service
