version: '2'
services:
  ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap
    environment:
      - LDAP_ORGANISATION=fmss
      - LDAP_DOMAIN=fmss.com
      - "LDAP_BASE_DN=dc=fmss,dc=com"
      - LDAP_ADMIN_PASSWORD=fmss
    ports:
      - 389:389
      - 636:636
